# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/logo_miccall.png"
    high_res_favicon: "/img/logo_miccall.png"
    apple_touch_icon: "/img/logo_miccall.png"
    keywords: Meowshmallow 喵菓子

Intro:
    name: 喵菓子工作室へ
    slogan: "我們只是個致力於做個軟萌的AVG小團隊 <br/> "
    HeadButton: Meowshmallow

Nav:
    Home_name: 主頁
    is_use_categories : true 
    categories_name: 分類
    is_use_archives : false
    archives_name: 歸檔
    
    icon:
        github: 
            use: false
            link: https://github.com/miccall
        Twitter:
            use: false
            link: 
        Facebook:
            use: true
            link: https://github.com/miccall
        Instagram:
            use: false
            link:
    pages:
        簡歷: 
            link: "/about/"
        團隊 :
            link: "/group/"
        圖庫 :
            link: "/gallery/"
        標籤:
            link: "/tag/"
        #自定义标签名
        #   link：“路径”

MainFirst:
    description: 本工作室是由一群大學生所組成的遊戲製作工作室
    name: Meowshmallow Studio
    pic_url: https://vectr.com/armecyan/e6YqDLW0lY.svg?width=640&height=640&select=e6YqDLW0lYpage0
    goto_ulr: ""

Gallery :
    title: 喵菓子圖庫 
    description: 相關圖像資料都會放這邊呦 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: disqus_click
    shortname: http-miccall-tech 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
